import type { StoreCategory, StoreProduct } from "./medusa";

/**
 * Fixture catalog — Imran Electric Store (PKR).
 *
 * Used ONLY as a fallback when the Medusa backend is unreachable or
 * unconfigured, so pages always render. Shape matches StoreProduct exactly;
 * lib/medusa.ts normalizes real Medusa data into the same shape.
 *
 * Prices are in major currency units (rupees).
 */

export const fixtureCategories: StoreCategory[] = [
  {
    id: "cat-inverters",
    name: "Inverters",
    handle: "inverters",
    slug: "inverters",
    description:
      "Solar hybrid inverters, UPS inverters and stabilizers for homes, shops and offices.",
    image: "/images/categories/inverters.svg",
    seoTitle: "Buy Inverters Online in Pakistan | Solar & UPS Inverters",
    seoDescription:
      "Shop solar hybrid inverters and UPS inverters online in Pakistan. Genuine brands, official warranty, best prices at Imran Electric Store.",
  },
  {
    id: "cat-solar-panels",
    name: "Solar Panels",
    handle: "solar-panels",
    slug: "solar-panels",
    description:
      "Mono PERC and polycrystalline solar panels from 180W to 550W for residential and commercial systems.",
    image: "/images/categories/solar-panels.svg",
    seoTitle: "Solar Panels Price in Pakistan | 180W – 550W Panels",
    seoDescription:
      "Buy genuine solar panels online in Pakistan. Mono PERC & poly panels with warranty. Best solar panel prices at Imran Electric Store.",
  },
  {
    id: "cat-batteries",
    name: "Batteries",
    handle: "batteries",
    slug: "batteries",
    description:
      "Deep-cycle tubular batteries and LiFePO4 lithium batteries for solar and UPS backup.",
    image: "/images/categories/batteries.svg",
    seoTitle: "Solar & UPS Batteries Price in Pakistan | Tubular & Lithium",
    seoDescription:
      "Shop tubular and lithium batteries for solar/UPS systems. Long backup, official warranty, wholesale rates at Imran Electric Store.",
  },
  {
    id: "cat-led-lights",
    name: "LED Lights",
    handle: "led-lights",
    slug: "led-lights",
    description:
      "Energy-saving LED bulbs, flood lights, panel lights and street lights.",
    image: "/images/categories/led-lights.svg",
    seoTitle: "LED Lights Price in Pakistan | Bulbs, Flood & Panel Lights",
    seoDescription:
      "Buy LED bulbs, flood lights and panel lights online in Pakistan. Energy efficient, long life, best prices at Imran Electric Store.",
  },
  {
    id: "cat-fans",
    name: "Fans",
    handle: "fans",
    slug: "fans",
    description:
      "Ceiling fans, pedestal fans and exhaust fans with pure copper winding.",
    image: "/images/categories/fans.svg",
    seoTitle: "Ceiling & Pedestal Fans Price in Pakistan",
    seoDescription:
      "Shop ceiling fans and pedestal fans online in Pakistan. Copper winding motors, high air delivery, warranty at Imran Electric Store.",
  },
  {
    id: "cat-switches",
    name: "Switches & Sockets",
    handle: "switches",
    slug: "switches",
    description:
      "Modular switches, sockets, plates and switchboards for modern wiring.",
    image: "/images/categories/switches.svg",
    seoTitle: "Switches & Sockets Price in Pakistan | Modular Plates",
    seoDescription:
      "Buy modular switches, sockets and plates online in Pakistan. Safe, durable and stylish designs at Imran Electric Store.",
  },
  {
    id: "cat-accessories",
    name: "Electrical Accessories",
    handle: "accessories",
    slug: "accessories",
    description:
      "Wires, breakers, holders, plugs and everyday electrical accessories.",
    image: "/images/categories/accessories.svg",
    seoTitle: "Electrical Accessories Online in Pakistan",
    seoDescription:
      "Shop wires, breakers, holders and electrical accessories online in Pakistan at Imran Electric Store.",
  },
];

export const fixtureProducts: StoreProduct[] = [
  {
    id: "prod-voltmax-hybrid-5kw",
    handle: "voltmax-hybrid-5kw-solar-inverter",
    title: "VoltMax 5kW Hybrid Solar Inverter (VM-5000)",
    brand: "VoltMax",
    model: "VM-5000",
    sku: "VM-5KW-HYB-001",
    shortDescription:
      "5kW pure sine wave hybrid solar inverter with dual MPPT — runs home load on solar by day, grid/battery by night.",
    description:
      "The VoltMax VM-5000 is a 5kW hybrid solar inverter built for Pakistani homes and small businesses. Dual MPPT trackers harvest maximum energy from up to 5500W of solar panels, while the pure sine wave output safely runs sensitive electronics, motors and LED lighting. Works with or without batteries, supports net metering, and the smart LCD + WiFi monitoring shows live generation on your phone.",
    thumbnail: "/images/products/voltmax-hybrid-5kw.svg",
    images: [
      { url: "/images/products/voltmax-hybrid-5kw.svg", alt: "VoltMax 5kW Hybrid Solar Inverter front view" },
      { url: "/images/products/voltmax-hybrid-5kw-2.svg", alt: "VoltMax 5kW Hybrid Solar Inverter side terminals" },
    ],
    price: 185000,
    salePrice: 169000,
    currency: "PKR",
    inStock: true,
    stockQty: 14,
    categoryId: "cat-inverters",
    category: { id: "cat-inverters", name: "Inverters", handle: "inverters" },
    specifications: [
      { name: "Rated Power", value: "5000W / 5kVA" },
      { name: "Output Waveform", value: "Pure sine wave" },
      { name: "MPPT Trackers", value: "Dual MPPT, 5500W max PV input" },
      { name: "Battery Voltage", value: "48V DC" },
      { name: "Charging Current", value: "80A MPPT + 60A AC" },
      { name: "Display", value: "LCD + WiFi monitoring" },
      { name: "Protection", value: "Overload, short-circuit, over-temp, reverse polarity" },
      { name: "Net Metering", value: "Supported" },
    ],
    attributes: { wattage: "5000W", type: "Hybrid", "battery-voltage": "48V" },
    weight: "13.5 kg",
    dimensions: "42 × 34 × 12 cm",
    warranty: "2 years official brand warranty",
    relatedIds: ["prod-voltmax-ups-3kva", "prod-solarstar-550w-mono", "prod-powercell-tubular-200ah"],
    rating: 4.8,
    reviewCount: 26,
    isFeatured: true,
    isBestSeller: true,
    seoTitle: "VoltMax 5kW Hybrid Solar Inverter Price in Pakistan | VM-5000",
    seoDescription:
      "Buy VoltMax 5kW hybrid solar inverter (VM-5000) online in Pakistan at Rs 169,000. Dual MPPT, pure sine wave, WiFi monitoring, 2-year warranty.",
  },
  {
    id: "prod-voltmax-ups-3kva",
    handle: "voltmax-3kva-ups-inverter",
    title: "VoltMax 3kVA UPS Inverter (Simulated Sine Wave)",
    brand: "VoltMax",
    model: "VU-3000",
    sku: "VM-3KVA-UPS-002",
    shortDescription:
      "3kVA UPS inverter for uninterrupted backup of fans, lights, TVs and computers during load shedding.",
    description:
      "The VoltMax VU-3000 is a reliable 3kVA UPS inverter designed for everyday load-shedding backup. It switches to battery in under 10 milliseconds, runs ceiling fans, LED lights, LED TV and computers smoothly, and recharges batteries quickly when power returns. Ideal paired with two 200Ah tubular batteries for 4–6 hours of backup.",
    thumbnail: "/images/products/voltmax-ups-3kva.svg",
    images: [
      { url: "/images/products/voltmax-ups-3kva.svg", alt: "VoltMax 3kVA UPS inverter front view" },
    ],
    price: 98500,
    currency: "PKR",
    inStock: true,
    stockQty: 22,
    categoryId: "cat-inverters",
    category: { id: "cat-inverters", name: "Inverters", handle: "inverters" },
    specifications: [
      { name: "Rated Power", value: "3kVA / 2400W" },
      { name: "Output Waveform", value: "Simulated sine wave" },
      { name: "Battery Voltage", value: "24V DC" },
      { name: "Transfer Time", value: "< 10 ms" },
      { name: "Charging Current", value: "20A smart charging" },
      { name: "Protection", value: "Overload, deep-discharge, short-circuit" },
    ],
    attributes: { wattage: "2400W", type: "UPS", "battery-voltage": "24V" },
    weight: "18 kg",
    dimensions: "38 × 30 × 22 cm",
    warranty: "1 year official brand warranty",
    relatedIds: ["prod-voltmax-hybrid-5kw", "prod-powercell-tubular-200ah", "prod-powercell-lithium-100ah"],
    rating: 4.5,
    reviewCount: 18,
    isBestSeller: true,
    seoTitle: "VoltMax 3kVA UPS Inverter Price in Pakistan | VU-3000",
    seoDescription:
      "Buy VoltMax 3kVA UPS inverter online in Pakistan. Fast <10ms transfer, 24V system, ideal for home load-shedding backup. 1-year warranty.",
  },
  {
    id: "prod-solarstar-550w-mono",
    handle: "solarstar-550w-mono-perc-solar-panel",
    title: "SolarStar 550W Mono PERC Solar Panel (Half-Cell)",
    brand: "SolarStar",
    model: "SS-550M",
    sku: "SS-550W-MONO-003",
    shortDescription:
      "550W mono PERC half-cell solar panel — high efficiency, 25-year performance warranty.",
    description:
      "The SolarStar SS-550M is a 550-watt monocrystalline PERC half-cell panel delivering up to 21.3% module efficiency. Half-cell technology reduces heat losses and improves shade tolerance, making it ideal for Pakistani rooftops. PID-resistant, hail-tested and backed by a 25-year linear performance warranty.",
    thumbnail: "/images/products/solarstar-550w-mono.svg",
    images: [
      { url: "/images/products/solarstar-550w-mono.svg", alt: "SolarStar 550W mono PERC solar panel" },
    ],
    price: 46500,
    salePrice: 43900,
    currency: "PKR",
    inStock: true,
    stockQty: 60,
    categoryId: "cat-solar-panels",
    category: { id: "cat-solar-panels", name: "Solar Panels", handle: "solar-panels" },
    specifications: [
      { name: "Peak Power", value: "550W" },
      { name: "Cell Technology", value: "Mono PERC half-cell" },
      { name: "Module Efficiency", value: "21.3%" },
      { name: "Open Circuit Voltage", value: "49.9V" },
      { name: "Frame", value: "Anodized aluminium, 35mm" },
      { name: "Connector", value: "MC4 compatible" },
      { name: "Certifications", value: "IEC 61215 / 61730, PID resistant" },
    ],
    attributes: { wattage: "550W", type: "Mono PERC", cells: "Half-cell" },
    weight: "27.5 kg",
    dimensions: "227.9 × 113.4 × 3.5 cm",
    warranty: "12 years product + 25 years performance warranty",
    relatedIds: ["prod-solarstar-180w-poly", "prod-voltmax-hybrid-5kw", "prod-powercell-lithium-100ah"],
    rating: 4.9,
    reviewCount: 41,
    isFeatured: true,
    isBestSeller: true,
    seoTitle: "550W Solar Panel Price in Pakistan | SolarStar Mono PERC",
    seoDescription:
      "Buy SolarStar 550W mono PERC solar panel online in Pakistan at Rs 43,900. 21.3% efficiency, half-cell, 25-year performance warranty.",
  },
  {
    id: "prod-solarstar-180w-poly",
    handle: "solarstar-180w-poly-solar-panel",
    title: "SolarStar 180W Polycrystalline Solar Panel",
    brand: "SolarStar",
    model: "SS-180P",
    sku: "SS-180W-POLY-004",
    shortDescription:
      "180W polycrystalline panel — affordable choice for small DC systems, fans and lighting.",
    description:
      "The SolarStar SS-180P 180W polycrystalline panel is the economical pick for small solar setups: DC fans, LED lighting, mobile charging and small UPS charging. Sturdy aluminium frame and tempered glass stand up to dust, heat and monsoon rain.",
    thumbnail: "/images/products/solarstar-180w-poly.svg",
    images: [
      { url: "/images/products/solarstar-180w-poly.svg", alt: "SolarStar 180W polycrystalline solar panel" },
    ],
    price: 18500,
    currency: "PKR",
    inStock: true,
    stockQty: 85,
    categoryId: "cat-solar-panels",
    category: { id: "cat-solar-panels", name: "Solar Panels", handle: "solar-panels" },
    specifications: [
      { name: "Peak Power", value: "180W" },
      { name: "Cell Technology", value: "Polycrystalline" },
      { name: "Module Efficiency", value: "17.2%" },
      { name: "Open Circuit Voltage", value: "22.8V" },
      { name: "Frame", value: "Anodized aluminium, 30mm" },
    ],
    attributes: { wattage: "180W", type: "Polycrystalline" },
    weight: "12 kg",
    dimensions: "148 × 67 × 3 cm",
    warranty: "10 years product + 20 years performance warranty",
    relatedIds: ["prod-solarstar-550w-mono", "prod-voltmax-ups-3kva"],
    rating: 4.4,
    reviewCount: 12,
    seoTitle: "180W Solar Panel Price in Pakistan | SolarStar Poly",
    seoDescription:
      "Buy SolarStar 180W polycrystalline solar panel online in Pakistan at Rs 18,500. Ideal for small DC systems and UPS charging.",
  },
  {
    id: "prod-powercell-tubular-200ah",
    handle: "powercell-200ah-tall-tubular-battery",
    title: "PowerCell 200Ah Tall Tubular Battery (12V)",
    brand: "PowerCell",
    model: "PC-T200",
    sku: "PC-200AH-TUB-005",
    shortDescription:
      "200Ah tall tubular battery — deep-cycle backup for UPS and solar systems.",
    description:
      "The PowerCell PC-T200 is a 200Ah tall tubular lead-acid battery engineered for deep daily cycling in UPS and solar applications. Tubular positive plates resist shedding for a longer service life, and the high electrolyte reserve means less frequent topping-up — built for Pakistan's long load-shedding hours.",
    thumbnail: "/images/products/powercell-tubular-200ah.svg",
    images: [
      { url: "/images/products/powercell-tubular-200ah.svg", alt: "PowerCell 200Ah tall tubular battery" },
    ],
    price: 72500,
    salePrice: 68900,
    currency: "PKR",
    inStock: true,
    stockQty: 30,
    categoryId: "cat-batteries",
    category: { id: "cat-batteries", name: "Batteries", handle: "batteries" },
    specifications: [
      { name: "Capacity", value: "200Ah @ C20" },
      { name: "Voltage", value: "12V DC" },
      { name: "Technology", value: "Tall tubular, deep-cycle" },
      { name: "Cycle Life", value: "1500+ cycles @ 50% DoD" },
      { name: "Container", value: "Heat-sealed PPCP" },
    ],
    attributes: { capacity: "200Ah", voltage: "12V", type: "Tubular" },
    weight: "62 kg",
    dimensions: "50 × 19 × 41 cm",
    warranty: "18 months replacement warranty",
    relatedIds: ["prod-voltmax-ups-3kva", "prod-voltmax-hybrid-5kw", "prod-powercell-lithium-100ah"],
    rating: 4.6,
    reviewCount: 33,
    isBestSeller: true,
    seoTitle: "200Ah Tubular Battery Price in Pakistan | PowerCell",
    seoDescription:
      "Buy PowerCell 200Ah tall tubular battery online in Pakistan at Rs 68,900. Deep-cycle, 1500+ cycles, 18-month warranty.",
  },
  {
    id: "prod-powercell-lithium-100ah",
    handle: "powercell-100ah-lifepo4-lithium-battery",
    title: "PowerCell 100Ah LiFePO4 Lithium Battery (12V)",
    brand: "PowerCell",
    model: "PC-L100",
    sku: "PC-100AH-LI-006",
    shortDescription:
      "100Ah LiFePO4 lithium battery with built-in BMS — half the weight, 4× the cycle life of lead-acid.",
    description:
      "The PowerCell PC-L100 packs 100Ah of lithium iron phosphate (LiFePO4) energy with a built-in smart BMS protecting against over-charge, over-discharge, short-circuit and temperature extremes. Delivers 4000+ cycles, charges 3× faster than lead-acid, and weighs just 13 kg — a true fit-and-forget upgrade for solar and UPS systems.",
    thumbnail: "/images/products/powercell-lithium-100ah.svg",
    images: [
      { url: "/images/products/powercell-lithium-100ah.svg", alt: "PowerCell 100Ah LiFePO4 lithium battery" },
    ],
    price: 95000,
    currency: "PKR",
    inStock: true,
    stockQty: 12,
    categoryId: "cat-batteries",
    category: { id: "cat-batteries", name: "Batteries", handle: "batteries" },
    specifications: [
      { name: "Capacity", value: "100Ah (1280Wh)" },
      { name: "Voltage", value: "12.8V DC" },
      { name: "Chemistry", value: "LiFePO4" },
      { name: "Cycle Life", value: "4000+ cycles @ 80% DoD" },
      { name: "BMS", value: "Built-in 100A smart BMS" },
      { name: "Charge Temp", value: "0°C to 55°C" },
    ],
    attributes: { capacity: "100Ah", voltage: "12.8V", type: "LiFePO4" },
    weight: "13 kg",
    dimensions: "33 × 17 × 22 cm",
    warranty: "3 years official warranty",
    relatedIds: ["prod-powercell-tubular-200ah", "prod-voltmax-hybrid-5kw", "prod-solarstar-550w-mono"],
    rating: 4.9,
    reviewCount: 9,
    isFeatured: true,
    seoTitle: "100Ah Lithium Battery Price in Pakistan | LiFePO4 PowerCell",
    seoDescription:
      "Buy PowerCell 100Ah LiFePO4 lithium battery online in Pakistan at Rs 95,000. 4000+ cycles, built-in BMS, 3-year warranty.",
  },
  {
    id: "prod-ostric-led-bulb-12w",
    handle: "ostric-12w-led-bulb",
    title: "Ostric 12W LED Bulb (Cool Daylight, B22)",
    brand: "Ostric",
    model: "OS-B12",
    sku: "OS-12W-BULB-007",
    shortDescription:
      "12W energy-saving LED bulb — bright cool daylight, B22 base, surge protected.",
    description:
      "The Ostric 12W LED bulb replaces a 100W incandescent while using 88% less electricity. High-lumen SMD chips deliver bright, flicker-free cool daylight (6500K), and built-in surge protection handles voltage fluctuations common in Pakistan. Rated for 25,000 hours of life.",
    thumbnail: "/images/products/ostric-led-bulb-12w.svg",
    images: [
      { url: "/images/products/ostric-led-bulb-12w.svg", alt: "Ostric 12W LED bulb" },
    ],
    price: 550,
    salePrice: 450,
    currency: "PKR",
    inStock: true,
    stockQty: 400,
    categoryId: "cat-led-lights",
    category: { id: "cat-led-lights", name: "LED Lights", handle: "led-lights" },
    specifications: [
      { name: "Wattage", value: "12W" },
      { name: "Lumens", value: "1200 lm" },
      { name: "Color Temperature", value: "6500K (Cool Daylight)" },
      { name: "Base", value: "B22" },
      { name: "Lifespan", value: "25,000 hours" },
      { name: "Voltage Range", value: "170–265V with surge protection" },
    ],
    attributes: { wattage: "12W", type: "Bulb", "color-temp": "6500K" },
    weight: "0.06 kg",
    dimensions: "6 × 6 × 11 cm",
    warranty: "1 year replacement warranty",
    relatedIds: ["prod-ostric-flood-30w", "prod-ostric-panel-18w"],
    rating: 4.7,
    reviewCount: 58,
    isBestSeller: true,
    seoTitle: "12W LED Bulb Price in Pakistan | Ostric",
    seoDescription:
      "Buy Ostric 12W LED bulb online in Pakistan at Rs 450. 1200 lumens cool daylight, surge protected, 1-year warranty.",
  },
  {
    id: "prod-ostric-flood-30w",
    handle: "ostric-30w-led-flood-light",
    title: "Ostric 30W LED Flood Light (IP66 Outdoor)",
    brand: "Ostric",
    model: "OS-F30",
    sku: "OS-30W-FLOOD-008",
    shortDescription:
      "30W IP66 waterproof LED flood light for outdoor, garden and security lighting.",
    description:
      "The Ostric 30W LED flood light throws bright, even illumination across courtyards, shops and building exteriors. IP66-rated die-cast aluminium housing shrugs off rain and dust, while the tempered glass lens and wide 120° beam keep outdoor spaces safe and visible all night.",
    thumbnail: "/images/products/ostric-flood-30w.svg",
    images: [
      { url: "/images/products/ostric-flood-30w.svg", alt: "Ostric 30W LED flood light" },
    ],
    price: 3850,
    salePrice: 3400,
    currency: "PKR",
    inStock: true,
    stockQty: 120,
    categoryId: "cat-led-lights",
    category: { id: "cat-led-lights", name: "LED Lights", handle: "led-lights" },
    specifications: [
      { name: "Wattage", value: "30W" },
      { name: "Lumens", value: "3000 lm" },
      { name: "IP Rating", value: "IP66 (dust & waterproof)" },
      { name: "Beam Angle", value: "120°" },
      { name: "Housing", value: "Die-cast aluminium" },
      { name: "Lifespan", value: "30,000 hours" },
    ],
    attributes: { wattage: "30W", type: "Flood Light", "ip-rating": "IP66" },
    weight: "0.8 kg",
    dimensions: "18 × 14 × 4 cm",
    warranty: "1 year replacement warranty",
    relatedIds: ["prod-ostric-led-bulb-12w", "prod-ostric-panel-18w"],
    rating: 4.6,
    reviewCount: 21,
    seoTitle: "30W LED Flood Light Price in Pakistan | Ostric IP66",
    seoDescription:
      "Buy Ostric 30W IP66 LED flood light online in Pakistan at Rs 3,400. Waterproof outdoor security lighting, 1-year warranty.",
  },
  {
    id: "prod-ostric-panel-18w",
    handle: "ostric-18w-led-panel-light",
    title: "Ostric 18W Round LED Panel Light (Surface)",
    brand: "Ostric",
    model: "OS-P18",
    sku: "OS-18W-PANEL-009",
    shortDescription:
      "18W slim round LED panel light — soft, glare-free ceiling lighting for rooms and offices.",
    description:
      "The Ostric 18W round panel light gives modern, glare-free illumination for bedrooms, kitchens and offices. The ultra-slim surface-mount design installs in minutes, and the edge-lit diffuser spreads light evenly with no dark spots.",
    thumbnail: "/images/products/ostric-panel-18w.svg",
    images: [
      { url: "/images/products/ostric-panel-18w.svg", alt: "Ostric 18W round LED panel light" },
    ],
    price: 1950,
    currency: "PKR",
    inStock: true,
    stockQty: 200,
    categoryId: "cat-led-lights",
    category: { id: "cat-led-lights", name: "LED Lights", handle: "led-lights" },
    specifications: [
      { name: "Wattage", value: "18W" },
      { name: "Lumens", value: "1800 lm" },
      { name: "Shape", value: "Round, surface mount" },
      { name: "Color Temperature", value: "4000K (Natural White)" },
      { name: "Lifespan", value: "25,000 hours" },
    ],
    attributes: { wattage: "18W", type: "Panel Light", "color-temp": "4000K" },
    weight: "0.4 kg",
    dimensions: "22.5 cm diameter × 2.5 cm",
    warranty: "1 year replacement warranty",
    relatedIds: ["prod-ostric-led-bulb-12w", "prod-ostric-flood-30w"],
    rating: 4.5,
    reviewCount: 16,
    seoTitle: "18W LED Panel Light Price in Pakistan | Ostric",
    seoDescription:
      "Buy Ostric 18W round LED panel light online in Pakistan at Rs 1,950. Slim surface mount, natural white, 1-year warranty.",
  },
  {
    id: "prod-aircool-ceiling-56",
    handle: "aircool-56-inch-ceiling-fan",
    title: "AirCool 56\" Ceiling Fan (Pure Copper Winding)",
    brand: "AirCool",
    model: "AC-C56",
    sku: "AC-56-CEIL-010",
    shortDescription:
      "56-inch ceiling fan with 99.9% pure copper winding — high air delivery, low noise, low power use.",
    description:
      "The AirCool 56-inch ceiling fan moves serious air while sipping electricity, thanks to its 99.9% pure copper winding motor and aerodynamically balanced blades. Double ball bearings keep it whisper-quiet and wobble-free, and the baked powder-coat finish resists rust for years.",
    thumbnail: "/images/products/aircool-ceiling-56.svg",
    images: [
      { url: "/images/products/aircool-ceiling-56.svg", alt: "AirCool 56 inch ceiling fan" },
    ],
    price: 13500,
    salePrice: 11900,
    currency: "PKR",
    inStock: true,
    stockQty: 45,
    categoryId: "cat-fans",
    category: { id: "cat-fans", name: "Fans", handle: "fans" },
    specifications: [
      { name: "Sweep", value: '56"' },
      { name: "Motor", value: "99.9% pure copper winding" },
      { name: "Speed", value: "330 RPM (high)" },
      { name: "Air Delivery", value: "230 CMM" },
      { name: "Power Consumption", value: "75W" },
      { name: "Bearings", value: "Double ball bearing" },
    ],
    attributes: { size: '56"', type: "Ceiling Fan", motor: "Copper" },
    weight: "7.2 kg",
    dimensions: '142 cm sweep, 30 cm downrod',
    warranty: "2 years motor warranty",
    relatedIds: ["prod-aircool-pedestal-18", "prod-ostric-led-bulb-12w"],
    rating: 4.7,
    reviewCount: 29,
    isFeatured: true,
    isBestSeller: true,
    seoTitle: "56 Inch Ceiling Fan Price in Pakistan | AirCool Copper",
    seoDescription:
      "Buy AirCool 56-inch ceiling fan online in Pakistan at Rs 11,900. Pure copper winding, 230 CMM air delivery, 2-year motor warranty.",
  },
  {
    id: "prod-aircool-pedestal-18",
    handle: "aircool-18-inch-pedestal-fan",
    title: "AirCool 18\" Pedestal Fan (5-Blade, Remote)",
    brand: "AirCool",
    model: "AC-P18R",
    sku: "AC-18-PED-011",
    shortDescription:
      "18-inch 5-blade pedestal fan with remote control — powerful, adjustable cooling anywhere.",
    description:
      "The AirCool 18-inch pedestal fan pairs a 5-blade design with a copper motor for strong, quiet airflow. Height-adjustable stand, 90° oscillation, 3 speed settings and a handy remote control make it perfect for living rooms, shops and offices.",
    thumbnail: "/images/products/aircool-pedestal-18.svg",
    images: [
      { url: "/images/products/aircool-pedestal-18.svg", alt: "AirCool 18 inch pedestal fan" },
    ],
    price: 8900,
    currency: "PKR",
    inStock: true,
    stockQty: 38,
    categoryId: "cat-fans",
    category: { id: "cat-fans", name: "Fans", handle: "fans" },
    specifications: [
      { name: "Blade Size", value: '18"' },
      { name: "Blades", value: "5" },
      { name: "Motor", value: "Copper winding" },
      { name: "Speeds", value: "3 + remote control" },
      { name: "Oscillation", value: "90°" },
      { name: "Height", value: "Adjustable 110–135 cm" },
    ],
    attributes: { size: '18"', type: "Pedestal Fan", motor: "Copper" },
    weight: "6.5 kg",
    dimensions: "46 × 46 × 110–135 cm",
    warranty: "1 year warranty",
    relatedIds: ["prod-aircool-ceiling-56"],
    rating: 4.4,
    reviewCount: 11,
    seoTitle: "18 Inch Pedestal Fan Price in Pakistan | AirCool Remote",
    seoDescription:
      "Buy AirCool 18-inch pedestal fan online in Pakistan at Rs 8,900. 5-blade, remote control, height adjustable, 1-year warranty.",
  },
  {
    id: "prod-switchpro-modular-8",
    handle: "switchpro-8-module-switch-plate",
    title: "SwitchPro 8-Module Switch Plate with Switches",
    brand: "SwitchPro",
    model: "SP-8M",
    sku: "SP-8MOD-PLT-012",
    shortDescription:
      "8-module modular switch plate with 6 switches + indicator — sleek, safe, easy to install.",
    description:
      "The SwitchPro 8-module plate brings modern modular wiring to any room: six 16A switches plus a neon indicator in a scratch-resistant glossy plate. Fire-retardant polycarbonate, silver-alloy contacts for long life, and standard back-box fitment make upgrades effortless.",
    thumbnail: "/images/products/switchpro-modular-8.svg",
    images: [
      { url: "/images/products/switchpro-modular-8.svg", alt: "SwitchPro 8 module switch plate" },
    ],
    price: 2450,
    salePrice: 2100,
    currency: "PKR",
    inStock: false,
    stockQty: 0,
    categoryId: "cat-switches",
    category: { id: "cat-switches", name: "Switches & Sockets", handle: "switches" },
    specifications: [
      { name: "Modules", value: "8" },
      { name: "Configuration", value: "6 × 16A switches + indicator" },
      { name: "Material", value: "Fire-retardant polycarbonate" },
      { name: "Contacts", value: "Silver alloy" },
      { name: "Fitment", value: "Standard 8-module back box" },
    ],
    attributes: { modules: "8", type: "Switch Plate" },
    weight: "0.35 kg",
    dimensions: "24 × 9 × 4 cm",
    warranty: "1 year warranty",
    relatedIds: ["prod-ostric-panel-18w", "prod-ostric-led-bulb-12w"],
    rating: 4.3,
    reviewCount: 7,
    seoTitle: "8 Module Switch Plate Price in Pakistan | SwitchPro",
    seoDescription:
      "Buy SwitchPro 8-module switch plate online in Pakistan at Rs 2,100. 6 switches + indicator, fire-retardant, 1-year warranty.",
  },
];
